apiVersion: v1
kind: Pod
metadata:
  name: kaniko-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu
                operator: In
                values:
                  - orin
  containers:
  - name: kaniko-demo
    image: gcr.io/kaniko-project/executor:latest
    args: ["--context=git://github.com/dickeyf/l4t-tensorflow.git",
            "--destination=dickeyf/l4t-tensorflow-models-official:2.14",
            "--dockerfile=Dockerfile"]
    volumeMounts:
      - name: registry-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: registry-secret
      secret:
        secretName: reg-credentials
        items:
          - key: .dockerconfigjson
            path: config.json